### ISSUE TITLE
Train on my own data，loss always NAN

### ISSUE THREAD

**Issue by xiexu666** [Stick-To/CenterNet-tensorflow#27]
Is there a pre-trained model about the centernet？When I train on my own data set, the loss function is always nan。

**Comment by liujianisme** [comment]
@xiexu666 I also met the same problem. In my situation, it's the sample error that caused loss NAN. I skipped these samples by calculating their losses and see if loss is NAN.

**Comment by zcunyi** [comment]
> @xiexu666 I also met the same problem. In my situation, it's the sample error that caused loss NAN. I skipped these samples by calculating their losses and see if loss is NAN.

Hi, have you trained your data success? 
I trained my own dataset according to the process， but there is always the error "InvalidArgumentError (see above for traceback): Cannot batch tensors with different shapes in component 0. First element had shape [578,768,3] and element 1 had shape [1062,796,3].
"

**Comment by zcunyi** [comment]
> Is there a pre-trained model about the centernet？When I train on my own data set, the loss function is always nan。

have you solved the error?

**Comment by MiniLisaBear** [comment]
Have you encountered this problem? When training with voc2007 data, the ground truth values are all -1, and the loss value is nan.

> @xiexu666 I also met the same problem. In my situation, it's the sample error that caused loss NAN. I skipped these samples by calculating their losses and see if loss is NAN.

Have you encountered this problem? When training with voc2007 data, the ground truth values are all -1, and the loss value is nan.

**Comment by xiexu666** [comment]
@MiniLisaBear @zcunyi  no, I have been too busy to solve this problem recently.

**Comment by MiniLisaBear** [comment]
@xiexu666 Thanks for your reply, I found the solution, when you filter loss nan in the issue you will also find

**Comment by congheng** [comment]
> @xiexu666 Thanks for your reply, I found the solution, when you filter loss nan in the issue you will also find

how to solve the problem, need your help

**Comment by MiniLisaBear** [comment]
see the detail from search in github filter with loss nan------------------ 原始邮件 ------------------
发件人: "congh"<notifications@github.com>
发送时间: 2020年1月6日(星期一) 下午4:32
收件人: "Stick-To/CenterNet-tensorflow"<CenterNet-tensorflow@noreply.github.com>;
抄送: "MiniLisaBear"<2511415342@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Stick-To/CenterNet-tensorflow] Train on my own data，loss always NAN (#27)


 
@xiexu666 Thanks for your reply, I found the solution, when you filter loss nan in the issue you will also find
  
how to solve the problem, need your help
 
&mdash;

**Comment by czy112** [comment]
i meet the same problem 
how to solve?
please

**Comment by phamkhactu** [comment]
I am a newbie, I follow the instruction, but i get error
- First: I download voc2007dataset
- Second: run utils.test_voc_utils.py. 
- Third: run Python test.py
```
 File "test.py", line 59, in <module>
    centernet = net.CenterNet(config, trainset_provider)
  File "/data/phamkhactu/CenterNet-tensorflow/CenterNet.py", line 44, in __init__
    self._define_inputs()
  File "/data/phamkhactu/CenterNet-tensorflow/CenterNet.py", line 63, in _define_inputs
    self.images, self.ground_truth = self.train_iterator.get_next()
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```
I think that i dataset isn't loaded. I need  help to fix it. Thanks in advance!!!

**Comment by luqioayun** [comment]
> I am a newbie, I follow the instruction, but i get error
> 
> * First: I download voc2007dataset
> * Second: run utils.test_voc_utils.py.
> * Third: run Python test.py
> 
> ```
>  File "test.py", line 59, in <module>
>     centernet = net.CenterNet(config, trainset_provider)
>   File "/data/phamkhactu/CenterNet-tensorflow/CenterNet.py", line 44, in __init__
>     self._define_inputs()
>   File "/data/phamkhactu/CenterNet-tensorflow/CenterNet.py", line 63, in _define_inputs
>     self.images, self.ground_truth = self.train_iterator.get_next()
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
>     name=name)
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
>     output_shapes=output_shapes, name=name)
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
>     op_def=op_def)
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
>     attrs, op_def, compute_device)
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
>     op_def=op_def)
>   File "/data/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
>     self._traceback = tf_stack.extract_stack()
> ```
> 
> I think that i dataset isn't loaded. I need help to fix it. Thanks in advance!!!

maybe you can use the python file "utils/tfrecord_voc_utils.py" to transfer the data to the tfrecord format~

**Comment by lvZic** [comment]
hi , I met the following error, and wonder how to fixe it.

------------------------- epoch 0 -------------------------
Traceback (most recent call last):
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [7,1] vs. shape[2] = [6,1]
	 [[{{node concat_1}}]]
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testretinanet.py", line 78, in <module>
    mean_loss = retinanet.train_one_epoch(lr)
  File "/mnt/fu03/lvzhen/test/Object-Detection-API-Tensorflow/RetinaNet.py", line 494, in _train_detection_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [7,1] vs. shape[2] = [6,1]
	 [[{{node concat_1}}]]

**Comment by xiexu666** [comment]
Recommend offical code ,that are more easier to use https://github.com/xingyizhou/CenterNet
